const NEW_MITIGATION_REQUEST = "NEW_MITIGATION_REQUEST",
    MITIGATION_REQ_DECLINED = "MITIGATION_REQ_DECLINED",
    MITIGATION_REQ_ACCEPTED = "MITIGATION_REQ_ACCEPTED",
    MITIGATION_REQ_IN_PROGRESS = "MITIGATION_REQ_IN_PROGRESS",
    MITIGATION_REQ_SUCCESSFUL = "MITIGATION_REQ_SUCCESSFUL";

module.exports = class MitigationRequest {
    static get NEW_MITIGATION_REQUEST() {
        return NEW_MITIGATION_REQUEST;
    }
    static get MITIGATION_REQ_DECLINED() {
        return MITIGATION_REQ_DECLINED;
    }
    static get MITIGATION_REQ_ACCEPTED() {
        return MITIGATION_REQ_ACCEPTED;
    }
    static get MITIGATION_REQ_IN_PROGRESS() {
        return MITIGATION_REQ_IN_PROGRESS;
    }
    static get MITIGATION_REQ_SUCCESSFUL() {
        return MITIGATION_REQ_SUCCESSFUL;
    }
};